# -*- coding: utf-8 -*-
"""月球儀にカーソルを合わせたとき、「1日の温度（アニメーション）」レイヤーの値を表示するための
粗いルックアップ JSON を作る（requirements v3.4 続き：常設ピンを廃止し、ホバー表示に一本化）。

data/diviner_global.csv.gz（0.5度グリッド・現地時間0〜23時の温度カーブ）を3度グリッドに間引き、
各セルの24時間分の温度カーブをそのまま格納する。実際の値をそのまま使うので、
「今の自転角に対応する現地時間」で2点を線形補間すれば、gen_diurnal_frames.py が
フレームを焼いたのと同じ考え方で「今この瞬間の温度」を再現できる（色からの逆算はしない）。

    python webapp/react/scripts/gen_diurnal_lookup.py

出力：webapp/react/src/data/diurnalLookup.generated.json
  { "step": 3, "cols": ["lat","lon","t00",..,"t23"], "cells": [[...26個...], ...] }
  他のデータ層と違い、このレイヤーを選んだときだけ動的 import で遅延読み込みする
  （静的テクスチャ24枚と同じ扱い。常にバンドルに含めない）。
"""
import json
import math
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "data" / "diviner_global.csv.gz"
OUT = ROOT / "webapp" / "react" / "src" / "data" / "diurnalLookup.generated.json"

STEP = 3  # 度。他のホバー用ルックアップ（siteEnvironment）と揃える
LT_COLS = [f"t_lt{h:02d}" for h in range(24)]


def main() -> None:
    df = pd.read_csv(SRC)
    df["glat"] = (df["lat"] / STEP).apply(math.floor) * STEP + STEP / 2
    df["glon"] = (df["lon"] / STEP).apply(math.floor) * STEP + STEP / 2
    agg = df.groupby(["glat", "glon"])[LT_COLS].mean().reset_index()

    cells = [
        [round(r.glat, 1), round(r.glon, 1)] + [round(float(getattr(r, c)), 1) for c in LT_COLS]
        for r in agg.itertuples(index=False)
    ]
    payload = {
        "_note": "generated by webapp/react/scripts/gen_diurnal_lookup.py from data/diviner_global.csv.gz — do not edit by hand",
        "step": STEP,
        "cols": ["lat", "lon", *[f"t{h:02d}" for h in range(24)]],
        "cells": cells,
    }
    OUT.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(cells)} cells, {OUT.stat().st_size/1024:.0f} KB)")


if __name__ == "__main__":
    main()
