# -*- coding: utf-8 -*-
"""data/site_environment.csv を粗いグリッドに間引いて、入口 Web アプリ用の JSON にする。
（requirements_v3.3.md I1：入口アプリの地点に site_environment の値を出せるようにする）

    python webapp/react/scripts/gen_site_env.py

出力：webapp/react/src/data/siteEnvironment.generated.json
  { "step": 3, "cols": ["lat","lon","tempAmp","nightMin","noonSun","earthElev","terrain",
    "slopeDeg","ageIndex"], "cells": [[...], ...] }
入口ページは「クリックした地点にいちばん近いセル」を引いて表示するだけなので粗くてよい
（月球儀にカーソルを合わせたときの「重ねているデータの値」表示にも同じJSONを使う。requirements
 v3.4 続き＝常設ピンを廃止してホバー表示に一本化）。
"""
import json
import math
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "data" / "site_environment.csv"
OUT = ROOT / "webapp" / "react" / "src" / "data" / "siteEnvironment.generated.json"

STEP = 3  # 度。3度グリッド（60x120=7200セル）


def _num_or_none(x):
    """NaN（極域の slope_deg 等）は JSON の null にする（bare NaN は JSON として不正）。"""
    return None if pd.isna(x) else round(float(x), 2)


def main() -> None:
    df = pd.read_csv(SRC)
    # 3度セルの中心に丸めて集約
    df["glat"] = (df["lat"] / STEP).apply(math.floor) * STEP + STEP / 2
    df["glon"] = (df["lon"] / STEP).apply(math.floor) * STEP + STEP / 2
    agg = df.groupby(["glat", "glon"]).agg(
        tempAmp=("temp_amp_K", "mean"),
        nightMin=("night_min_K", "mean"),
        noonSun=("noon_sun_elev_deg", "mean"),
        earthElev=("earth_elev_deg", "mean"),
        terrain=("区分", lambda s: s.mode().iat[0] if not s.mode().empty else ""),
        slopeDeg=("slope_deg", "mean"),
        ageIndex=("age_index", "mean"),
    ).reset_index()

    cells = [
        [round(r.glat, 1), round(r.glon, 1), round(r.tempAmp, 1),
         round(r.nightMin, 1), round(r.noonSun, 1), round(r.earthElev, 1), r.terrain,
         _num_or_none(r.slopeDeg), _num_or_none(r.ageIndex)]
        for r in agg.itertuples(index=False)
    ]
    payload = {
        "_note": "generated by webapp/react/scripts/gen_site_env.py from data/site_environment.csv — do not edit by hand",
        "step": STEP,
        "cols": ["lat", "lon", "tempAmp", "nightMin", "noonSun", "earthElev", "terrain",
                 "slopeDeg", "ageIndex"],
        "cells": cells,
    }
    OUT.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(cells)} cells, {OUT.stat().st_size/1024:.0f} KB)")


if __name__ == "__main__":
    main()
